DROP TABLE LOGS_OCENKA CASCADE CONSTRAINTS;

CREATE TABLE LOGS_OCENKA
(
  DT          DATE,
  DOMAIN      VARCHAR2(25 BYTE),
  USEROK      VARCHAR2(25 BYTE),
  PROG        VARCHAR2(20 BYTE),
  TEXT        VARCHAR2(400 BYTE),
  USEROK_FIO  VARCHAR2(150 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
