DROP TABLE OCENKA CASCADE CONSTRAINTS;

CREATE TABLE OCENKA
(
  GOD          NUMBER(4),
  ID_WORK      NUMBER(10),
  ZEX          NUMBER(3),
  TN           NUMBER(5),
  FIO          VARCHAR2(250 BYTE),
  DOLG         VARCHAR2(200 BYTE),
  FUNCT        VARCHAR2(100 BYTE),
  UU           VARCHAR2(4 BYTE),
  FUNCT_G      VARCHAR2(100 BYTE),
  KAT          VARCHAR2(30 BYTE),
  DIREKT       NUMBER(4),
  DATA_OCEN    DATE,
  FIO_OCEN     VARCHAR2(200 BYTE),
  DOLG_OCEN    VARCHAR2(200 BYTE),
  REZULT_OCEN  NUMBER(4,2),
  KPE_OCEN     NUMBER(5,2),
  KOMP_OCEN    NUMBER(5,2),
  EFECT        NUMBER(5,2),
  AVT_REIT     VARCHAR2(2 BYTE),
  SKOR_REIT    VARCHAR2(2 BYTE),
  KOM_REIT     VARCHAR2(2 BYTE),
  REZERV       NUMBER(1),
  DOLG_REZERV  VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
