DROP TABLE SP_DIREKT CASCADE CONSTRAINTS;

CREATE TABLE SP_DIREKT
(
  KOD     NUMBER(2),
  NAIM    VARCHAR2(100 BYTE),
  OTCHET  NUMBER(2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
