DROP TABLE SP_PDIREKT CASCADE CONSTRAINTS;

CREATE TABLE SP_PDIREKT
(
  ZEX       NUMBER(4),
  KOD_D     NUMBER(2),
  NAIM_ZEX  VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
